apiVersion: v2
name: quiz-backend
description: A Helm chart for the Quiz Backend application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 1.5.1