# Default values for quiz-backend
# This is a YAML-formatted file.

# -- Default values for common library chart
common:
  # -- Configure global settings
  global:
    # -- Set an override for the prefix of the fullname
    nameOverride: ""
    # -- Set an override for the fullname
    fullnameOverride: ""

# -- Configure controllers
controllers:
  main:
    # -- Enable the controller
    enabled: true
    # -- Controller type, can be deployment, statefulset, daemonset, etc.
    type: deployment
    # -- Number of replicas
    replicas: 1
    # -- Strategy for updating the deployment
    strategy: RollingUpdate
    # -- Rolling update configuration
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    # -- Pod annotations
    pod:
      annotations: { }
      securityContext: { }
    
    # -- Container configuration
    containers:
      main:
        # -- Container image
        image:
          repository: ghcr.io/vymalo/quiz-backend
          tag: latest
          pullPolicy: IfNotPresent
        
        # -- Container resources
        resources:
          limits:
            cpu: 800m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 512Mi
        
        # -- Container security context
        securityContext: { }
        
        # -- Container ports
        ports:
          - name: http
            protocol: TCP
            containerPort: 3000
        
        # -- Container probes
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /health/liveness
            port: http
          readiness:
            enabled: true
            type: HTTP
            path: /health/readiness
            port: http
          startup:
            enabled: true
            type: HTTP
            path: /health/startup
            port: http
        
        # -- Environment variables
        env:
          NODE_ENV: production
          
          # A smart model
          OPENAI_QUESTION_BASE_URL:
            valueFrom:
              configMapKeyRef:
                name: api-key-config
                key: url
          OPENAI_QUESTION_API_KEY:
            valueFrom:
              secretKeyRef:
                name: api-key-secret
                key: api-key
                optional: true
          OPENAI_QUESTION_MODEL: cogito:8b
          OPENAI_QUESTION_TOOLING: true

          # A smart model
          OPENAI_RESPONSE_BASE_URL:
            valueFrom:
              configMapKeyRef:
                name: api-key-config
                key: url
          OPENAI_RESPONSE_API_KEY:
            valueFrom:
              secretKeyRef:
                name: api-key-secret
                key: api-key
                optional: true
          OPENAI_RESPONSE_MODEL: cogito:8b
          OPENAI_RESPONSE_TOOLING: true

          # A tooling capable yet smart model 
          OPENAI_SUMMARIZER_BASE_URL:
            valueFrom:
              configMapKeyRef:
                name: api-key-config
                key: url
          OPENAI_SUMMARIZER_API_KEY:
            valueFrom:
              secretKeyRef:
                name: api-key-secret
                key: api-key
                optional: true
          OPENAI_SUMMARIZER_MODEL: llama3.1:8b-instruct-q4_K_M

          # A tooling capable yet smart model 
          OPENAI_EMBEDDING_BASE_URL:
            valueFrom:
              configMapKeyRef:
                name: api-key-config
                key: url
          OPENAI_EMBEDDING_API_KEY:
            valueFrom:
              secretKeyRef:
                name: api-key-secret
                key: api-key
                optional: true
          OPENAI_EMBEDDING_MODEL: bge-m3:567m

          CHROMA_HOST: localhost
          CHROMA_PORT: 8000
          CHROMA_DATABASE: ~
          CHROMA_COLLECTION_PREFIX: quizz_

          CACHE_TTL: 60000
          CACHE_REDIS_URL: redis://localhost:6379

# -- Image pull secrets
imagePullSecrets: [ ]

# -- Environment variables for the container (moved to controllers.main.containers.main.env)

# -- Configure service account
serviceAccount:
  # -- Enable service account creation
  create: true
  # -- Annotations to add to the service account
  annotations: { }
  # -- The name of the service account to use
  name: ""
  # -- Generate token for the service account
  generateToken: false

# -- Configure service
service:
  main:
    # -- Enable the service
    enabled: true
    # -- Configure which controller this service should target
    controller: main
    # -- Make this the primary service
    primary: true
    # -- Service type
    type: ClusterIP
    # -- Service ports
    ports:
      http:
        enabled: true
        port: 3000
        targetPort: 3000
    # -- Service annotations
    annotations: { }

# -- Configure ingress
ingress:
  main:
    # -- Enable ingress
    enabled: true
    # -- Ingress class name
    className: ""
    # -- Ingress annotations
    annotations: { }
    # -- Ingress hosts
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    # -- Ingress TLS configuration
    tls: [ ]

# -- Configure persistence
persistence:
  # -- Configure persistence items
  config:
    # -- Enable persistence for the config volume
    enabled: false
    # -- Storage Class for the config volume
    storageClass: ""
    # -- Access mode for the config volume
    accessMode: ReadWriteOnce
    # -- Size of the config volume
    size: 1Gi
    # -- Global mounts for the config volume
    globalMounts:
      - path: /app/config
    # -- Advanced mounts configuration
    advancedMounts: { }

# -- Node selector
nodeSelector: { }

# -- Tolerations
tolerations: [ ]

# -- Affinity
affinity: { }