# Default values for quiz-backend
# This is a YAML-formatted file.

global:
  # -- Set an override for the prefix of the fullname
  nameOverride: ""
  # -- Set an override for the fullname
  fullnameOverride: ""

# -- Configure image settings
image:
  # -- Image repository
  repository: quiz-backend
  # -- Image tag
  tag: latest
  # -- Image pull policy
  pullPolicy: IfNotPresent

# -- Image pull secrets
imagePullSecrets: []

# -- Environment variables for the container
env:
  # -- Set NODE_ENV for the application
  NODE_ENV: production

# -- Configure service account
serviceAccount:
  # -- Enable service account creation
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use
  name: ""

# -- Configure controller (deployment)
controller:
  # -- Controller type, can be deployment, statefulset, daemonset, etc.
  type: deployment
  # -- Number of replicas
  replicas: 1
  # -- Strategy for updating the deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  # -- Pod annotations
  podAnnotations: {}
  # -- Pod security context
  podSecurityContext: {}
  # -- Container security context
  securityContext: {}
  # -- Autoscaling configuration
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  # -- Container resources
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  # -- Container ports
  ports:
    http:
      port: 3000
      protocol: TCP
  # -- Container probes
  probes:
    liveness:
      enabled: true
      path: /
      port: http
    readiness:
      enabled: true
      path: /
      port: http
    startup:
      enabled: true
      path: /
      port: http

# -- Configure service
service:
  # -- Service type
  type: ClusterIP
  # -- Service port
  ports:
    http:
      port: 80
      targetPort: http
      protocol: TCP
  # -- Service annotations
  annotations: {}

# -- Configure ingress
ingress:
  # -- Enable ingress
  enabled: false
  # -- Ingress class name
  className: ""
  # -- Ingress annotations
  annotations: {}
  # -- Ingress hosts
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  # -- Ingress TLS configuration
  tls: []

# -- Configure persistence
persistence:
  # -- Enable persistence
  enabled: false
  # -- Persistence configuration
  config:
    enabled: false
    mountPath: /app/config
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""

# -- Configure metrics
metrics:
  # -- Enable metrics
  enabled: false
  # -- Service monitor configuration
  serviceMonitor:
    enabled: false

# -- Node selector
nodeSelector: {}

# -- Tolerations
tolerations: []

# -- Affinity
affinity: {}