---
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3001:3000'
    environment:
      OPENAI_QUESTION_BASE_URL: http://10.10.0.229:11434/v1
      OPENAI_QUESTION_API_KEY: 
      OPENAI_QUESTION_MODEL: gemma3:12b

      OPENAI_RESPONSE_BASE_URL: http://10.10.0.229:11434/v1
      OPENAI_RESPONSE_API_KEY: 
      OPENAI_RESPONSE_MODEL: gemma3:12b

      CHROMA_HOST: localhost
      CHROMA_PORT: 8000
      CHROMA_DATABASE: 
      CHROMA_COLLECTION: quizz

      BRAVE_SEARCH_API_KEY: 'sdsd'
      
    depends_on:
      chroma:
        condition: service_started

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      # The default config specifies a persist_directory of /data.
      # Read more about deployments: https://docs.trychroma.com/deployment
      - chroma-data:/data
    ports:
      - "8000:8000"
    healthcheck:
      # Adjust below to match your container port
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      IS_PERSISTENT: TRUE

volumes:
  chroma-data:
    driver: local
