---
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3001:3000'
    environment:
      CACHE_REDIS_URL: redis://redis:6379
    depends_on:
      chroma:
        condition: service_started

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      # The default config specifies a persist_directory of /data.
      # Read more about deployments: https://docs.trychroma.com/deployment
      - chroma-data:/data
    ports:
      - "8000:8000"
    environment:
      IS_PERSISTENT: TRUE
  
  admin:
    image: fengzhichao/chromadb-admin
    ports:
      - "3002:3001"
    depends_on:
      chroma:
        condition: service_started

  redis:
    image: redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  chroma-data:
    driver: local
  redis-data:
    driver: local
