apiVersion: v1
kind: Service
metadata:
  name: {{ include "quiz-backend.fullname" . }}
  labels:
    {{- include "quiz-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http.port }}
      targetPort: http
      protocol: {{ .Values.service.ports.http.protocol }}
      name: http
  selector:
    {{- include "quiz-backend.selectorLabels" . | nindent 4 }}